### ISSUE TITLE
MVP example of unicode unescaping would be helpful in the documentation

### ISSUE THREAD

**Issue by PeterGrace** [euank/snailquote#11]
I am trying to use snailquote::unescape() to take a string-representation of a unicode character and convert it into the actual unicode character.  However, my code is not doing what I would expect.  Here's the code:
```
use snailquote::escape;

fn main() {
    let string_val: String = String::from(r"\u{e9fe}");
    let str_val: &str = r"\u{e9fe}";
    println!("string_val is |{}|", string_val);
    println!("str_val is |{}|", str_val);

    match snailquote::unescape(string_val.as_str()) {
        Ok(e) => println!("string:Value unescaped is |{}|", e),
        Err(e) => println!("string:There was an error unescaping.")
    };

    match snailquote::unescape(str_val) {
        Ok(e) => println!("str:Value unescaped is |{}|", e),
        Err(e) => println!("str:There was an error unescaping.")
    };
}
```
The output for that command:
```
string_val is |\u{e9fe}|
str_val is |\u{e9fe}|
string:Value unescaped is |\u{e9fe}|
str:Value unescaped is |\u{e9fe}|
```

Whereas I would expect the output to be:
```
string_val is |\u{e9fe}|
str_val is |\u{e9fe}|
string:Value unescaped is ||
str:Value unescaped is ||
```

I'm certain that I must be doing something wrong -- can I get a hand with producing the desired output?

**Comment by PeterGrace** [comment]
I had a fellow rust programmer help me with it and it turns out I need to define the input strings like so:
```
fn main() {
    let string_val: String = String::from("\"\\u{e9fe}\"");
    let str_val: &str = "\"\\u{e9fe}\"";
```

**Comment by euank** [comment]
Glad you figured it out, @PeterGrace. I have a couple more thoughts based on the problem you described though, which hopefully you won't mind me typing out here :smiley: 

The fact that you have to add the extra seemingly-unnecessary quoting around it is because snailquote's "unescape" method isn't really meant to be used like this, but  rather to "unescape" the quoted text that it produced itself. There's a slight impedance mismatch between what this library's intent is and what you're trying to do.

For just converting the "\u{...}" format of a unicode character into a `char` type, snailquote seems a bit like overkill.

Unfortunately, the rust stdlib doesn't actually have a method that does exactly the unescaping you want, but it's not too bad to write one with something like: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=1efb0ac67d6da41115b13e660d6ecf5

There's also [`rustc_lexer::unescape::unescape_char`](https://github.com/rust-lang/rust/blob/1b6b06a03a00a7c9f156bff130b72e90b79e1127/compiler/rustc_lexer/src/unescape.rs#L97-L103), which seems to exactly match what you're trying to do (though importing the whole crate for just that function may also be a bit overkill).

Good luck with whatever it is you're building!
